name: Feature Branch CI

on:
  push:
    branches:
      - 'feature/**'

jobs:
  run-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest --cov=your_module tests/

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov

  create-pr:
    needs: run-tests
    if: success()
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Create Pull Request with GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          
          # Check if PR already exists
          PR_EXISTS=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number' || true)

          if [ -z "$PR_EXISTS" ]; then
            gh pr create \
              --base main \
              --head "$BRANCH_NAME" \
              --title "Auto PR: Merge $BRANCH_NAME into main" \
              --body "This PR was created automatically after successful test run."
          else
            echo "PR already exists: #$PR_EXISTS"
          fi

      - name: Enable Auto-Merge (Optional)
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number' || true)

          if [ -n "$PR_NUMBER" ]; then
            gh pr merge "$PR_NUMBER" --auto --squash || true
            echo "Auto-merge enabled for PR #$PR_NUMBER"
          else
            echo "No PR found to enable auto-merge."
          fi
