name: CI Pipeline for FastAPI App

on:
  push:
    branches:
      - master  # Trigger on push to the main branch
  pull_request:
    branches:
      - master  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Docker
      uses: docker/setup-qemu-action@v1

    - name: Build Docker image
      run: |
        docker build -t fastapi-app .

    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 fastapi-app
        sleep 10  # Wait for the app to start

    - name: Test FastAPI App
      run: |
        curl --fail http://localhost:8000 || exit 1
        echo "FastAPI app is running!"

    - name: Stop Docker container
      run: |
        docker ps -q --filter "ancestor=fastapi-app" | xargs docker stop
