name: CI Pipeline with Timestamp Tags

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: myapp
      ACR_LOGIN_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python for testing
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # 3. Run tests
      - name: Run tests
        run: pytest

      # 4. Set image tag using date-time
      - name: Generate image tag
        id: tag
        run: echo "IMAGE_TAG=$(date -u +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      # 5. Azure login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      # 6. Docker build
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # 7. Push to Azure Container Registry
      - name: Push to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      # 8. Deploy to Azure Container App
      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{ secrets.CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
