name: CI/CD Pipeline for FastAPI App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: |
        docker build -t my-fastapi-app .

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push Docker image to Azure Container Registry
      run: |
        docker tag my-fastapi-app:latest ${ACR_NAME}.azurecr.io/my-fastapi-app:latest
        docker push ${ACR_NAME}.azurecr.io/my-fastapi-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name ${CONTAINER_APP_NAME} \
          --resource-group ${RESOURCE_GROUP} \
          --image ${ACR_NAME}.azurecr.io/my-fastapi-app:latest