name: Deploy FastAPI to Azure Container Apps

on:
  push:
    branches:
      - master  # Change this if you're using a different branch

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"
